name: Publish Pre-release

on:
    #     schedule:
    #         - cron: "0 0 * * *"
    workflow_dispatch:
        inputs:
            bumprelease:
                type: choice
                description: Bump a package version
                required: true
                default: prerelease
                options:
                    - prerelease
                    - prepatch
                    - preminor
                    - premajor

env:
    bumprelease: ${{ github.event.inputs.bumprelease || 'prerelease' }}
    NPM_USER: ${{ secrets.NPM_USER }}
    NPM_PASS: ${{ secrets.NPM_PASS }}
    NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

jobs:
    check_date:
        runs-on: ubuntu-latest
        name: Check latest commit
        outputs:
            should_run: ${{ steps.should_run.outputs.should_run }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Latest Commit
              run: echo ${{ github.sha }}

            - id: should_run
              continue-on-error: true
              name: Check latest commit is less than a day
              if: ${{ github.event_name == 'schedule' }}
              run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

    main:
        needs: check_date
        if: ${{ needs.check_date.outputs.should_run != 'false' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"

            - name: Login to GitHub Private NPM Registry
              shell: bash
              run: |
                  npm install -g npm-cli-login
                  npm-cli-login -u $NPM_USER -p $NPM_PASS -e "$NPM_EMAIL" -r "https://npm.pkg.github.com" -s "@betterdiscordbuilder"

            - name: Bump a package version
              id: bump_version
              run: |
                  npm install -g version-bump-prompt
                  bump $bumprelease ./pre-release/package.json

            - name: Install Dependencies
              run: npm install
            - name: Run script
              if: steps.bump_version.outcome == 'success'
              id: build_prerelease
              run: npm run script:publish_prerelease

            - uses: nyaa8/package-version@v1
              if: steps.build_prerelease.outcome == 'success'
              id: package_version
              with:
                  path: "./pre-release/package.json"
                  follow-symlinks: "false"

            # - name: Create Release
            #   if: steps.package_version.outcome == 'success'
            #   id: create_release
            #   uses: actions/create-release@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #       tag_name: v${{ env.PACKAGE_VERSION }}
            #       release_name: ${{ env.PACKAGE_VERSION }}
            #       body: "##### ${{ env.bumprelease }}"
            #       draft: false
            #       prerelease: true

            # - name: Upload Release Asset
            #   if: steps.create_release.outcome == 'success'
            #   id: upload_release_asset
            #   uses: actions/upload-release-asset@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #       upload_url: ${{ steps.create_release.outputs.upload_url }}
            #       asset_path: ./pre-release/RPCPcStatus.plugin.js
            #       asset_name: RPCPcStatus.plugin.js
            #       asset_content_type: text/javascript

            - name: Automatically Commit Changed
              if: steps.package_version.outcome == 'success'
              id: commit_changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "New Pre release ${{ env.PACKAGE_VERSION }}"
                  commit_user_name: GitHub Actions
                  commit_user_email: actions@github.com
                  commit_author: GitHub Actions <actions@github.com>
                  skip_checkout: true

            - name: Create tag
              if: steps.commit_changed.outcome == 'success'
              uses: rickstaa/action-create-tag@v1
              with:
                  tag: v${{ env.PACKAGE_VERSION }}
